version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    container_name: front
    build:
      context: ../front
    image: front
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ../front:/app
      - frontend_node_modules:/app/node_modules

  back:
    depends_on:
      - db
    container_name: back
    build:
      context: ../back
    image: back
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "4242:4242"
    volumes:
      - ../back:/app
      - backend_node_modules:/app/node_modules

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
